### PR TITLE
Add help links

### PR DESCRIPTION
**Pull request by bubelov**
**Does this PR address a related issue?**

**A description of the changes proposed in the pull request**

**Screenshots**

**Additional context**

### CODE REVIEW

**Comment by secondl1ght** [comment]
I was thinking we could just turn the description ex. 'Outdated location' into a link that leads to the Wiki. What do you think? Is it better to have a dedicated column?

**Comment by bubelov** [comment]
I'm not sure if the description field is necessary since we have a type field. It would be stupid to send 100+ descriptions when we'll need to localize the app, and it's not good for sync and local storage

**Comment by bubelov** [comment]
So, the description column can be removed in the future, or it can be derived from the type field client-side. As for the link, I don't really care, but it's better if we put something actionable there as soon as possible

**Comment by secondl1ght** [comment]
This is a good idea about deriving the descriptions from the types on the client-side. Just let me know when you want to deprecate that field in the backend and I will make the updates on the frontend.

**Pull request merged**
