### PR TITLE
feat: add husky for git hooks

### PR DESCRIPTION
**Pull request by thebrandonlucas**
**A description of the changes proposed in the pull request**

Adds the [husky](https://www.npmjs.com/package/husky) dependency with automated prettier formatting for consistency and increased maintainability. This can easily be extended to include any scripts we want to run prior to committing (such as ESLint, tests, or Typescript checks if we choose to add)

Screen Shot 2022-09-23 at 3 35 51 PM

### CODE REVIEW

**Comment by secondl1ght** [comment]
I checked out Husky and it looks good - one thing, can you change `npm run format` to `yarn format` in the pre-commit hook because we use yarn and not npm on this project. Great idea to add this! I didn't want to add anything too heavy for something that can be done with a simple command but this seems to be a very lightweight package.

**Review by secondl1ght — CHANGES_REQUESTED** [review]
See comment for requested changes

**Comment by thebrandonlucas** [comment]
> I checked out Husky and it looks good - one thing, can you change npm run format to yarn format in the pre-commit hook because we use yarn and not npm on this project. Great idea to add this! I didn't want to add anything too heavy for something that can be done with a simple command but this seems to be a very lightweight package.

Done! Thanks for the catch.

**Comment by thebrandonlucas** [comment]
> I checked out Husky and it looks good - one thing, can you change `npm run format` to `yarn format` in the pre-commit hook because we use yarn and not npm on this project. Great idea to add this! I didn't want to add anything too heavy for something that can be done with a simple command but this seems to be a very lightweight package.

I definitely hear you about not wanting to add dependencies, but what's interesting about husky is that it can help a lot with maintainability. If/when we want to add unit tests, Eslint, or Typescript checks (for example), we could do all of that on each commit and have a lot higher code quality/consistency. Happy to tackle any of those things if we'd like to pursue any of those!

**Comment by secondl1ght** [comment]
@thebrandonlucas sorry I just checked this PR and realized the email notifications were going to my junk folder for some reason!! 😕 Will merge later today! ❤️

**Comment by thebrandonlucas** [comment]
> @thebrandonlucas sorry I just checked this PR and realized the email notifications were going to my junk folder for some reason!! 😕 Will merge later today! ❤️

No worries :)

**Review by secondl1ght — APPROVED** [review]
LGTM!

**Pull request merged**
